// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt7Hw8DXTIk7W-qFAdzTbWkHHbfjPRUKw',
    appId: '1:519899488299:web:36cffd7ecc4a42ab084a6e',
    messagingSenderId: '519899488299',
    projectId: 'relatorio-de-atendimento-a8666',
    authDomain: 'relatorio-de-atendimento-a8666.firebaseapp.com',
    storageBucket: 'relatorio-de-atendimento-a8666.appspot.com',
    measurementId: 'G-953XEQK802',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh2FDNWhBo-k80qfGjHeoLnDba2MmoO-o',
    appId: '1:519899488299:android:cb3bdbd69d60f8b6084a6e',
    messagingSenderId: '519899488299',
    projectId: 'relatorio-de-atendimento-a8666',
    storageBucket: 'relatorio-de-atendimento-a8666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAULGnB9nVv0zwdxsUMD3jagk_DUk2aJao',
    appId: '1:519899488299:ios:c0af085c98377215084a6e',
    messagingSenderId: '519899488299',
    projectId: 'relatorio-de-atendimento-a8666',
    storageBucket: 'relatorio-de-atendimento-a8666.appspot.com',
    iosClientId: '519899488299-u5b2d9rghommtkqt8aem071bv6620dji.apps.googleusercontent.com',
    iosBundleId: 'com.gabrielssouza.relatorioDeAatendimento',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAULGnB9nVv0zwdxsUMD3jagk_DUk2aJao',
    appId: '1:519899488299:ios:c0af085c98377215084a6e',
    messagingSenderId: '519899488299',
    projectId: 'relatorio-de-atendimento-a8666',
    storageBucket: 'relatorio-de-atendimento-a8666.appspot.com',
    iosClientId: '519899488299-u5b2d9rghommtkqt8aem071bv6620dji.apps.googleusercontent.com',
    iosBundleId: 'com.gabrielssouza.relatorioDeAatendimento',
  );
}
